export const DEVELOPER_PARAGRAPHS = [
  // 1. Clean Code & Refactoring (~190 words)
  `Clean code is not written in a single pass; it is the result of continuous refactoring, thoughtful naming, and ruthless simplification. As developers, we spend far more time reading code than writing it. Therefore, writing readable code is a service we render to our future selves and our colleagues. When we choose descriptive variable names, write short functions with single responsibilities, and avoid unnecessary complexity, we reduce the cognitive load required to understand our systems. Good code should read like well-written prose, hiding details behind clean abstractions and expressing intent clearly. Over-engineering is the enemy of velocity. We must resist the urge to build complex architectures for problems we do not yet have, adhering instead to the principles of YAGNI and KISS. Every line of code we write is a liability, a potential source of bugs, and a maintenance cost. By keeping our codebase minimal, expressive, and covered by a robust suite of automated unit tests, we build resilient systems that can adapt to changing requirements. Refactoring is not a chore to be scheduled; it is an organic, everyday habit of professional craftsmanship.`,

  // 2. AI & Agentic Systems (~200 words)
  `The transition from traditional software development to agentic artificial intelligence represents a paradigm shift in human-computer collaboration. Developers are no longer just writing step-by-step algorithms; they are designing cognitive runtimes, defining systemic guardrails, and guiding autonomous agents that can plan, execute, and verify code. In this new era, coding becomes an interactive dialogue where AI engines handle repetitive tasks and boilerplate generation, while human programmers focus on architecture, system design, security protocols, and domain modeling. This acceleration enables rapid prototyping and shortens the feedback loop between conceptualization and implementation. However, the developer's role remains critical as the ultimate orchestrator. We must ensure these intelligent agents operate within strict ethical bounds, maintain proper security controls, and do not introduce subtle logical vulnerabilities. Designing systems that integrate agentic workflows requires an understanding of prompt engineering, contextual state management, and real-time validation layers. The future belongs to developers who can effectively pair-program with AI, leveraging machine speed for execution and human judgment for governance, creating software that is far more adaptive and powerful than anything we have built before.`,

  // 3. Algorithms & Optimization (~195 words)
  `In the realm of computer science, algorithms are the silent engines that power our digital world. Designing efficient algorithms requires a deep understanding of time and space complexity, expressed through Big O notation. When dealing with large-scale datasets, the difference between an algorithm that runs in linear time and one that runs in quadratic time can mean the difference between a responsive user interface and an application crash. Optimizing performance is a delicate balance of choosing the right data structures, minimizing memory allocations, and understanding processor cache lines. We must avoid premature optimization, focusing first on correctness and clarity. Only when bottlenecks are identified through rigorous profiling should we rewrite code for speed. Techniques like memoization, divide-and-conquer, dynamic programming, and greedy heuristics allow us to solve complex problems in optimal ways. However, performance gains must not come at the cost of readability. A highly optimized, convoluted algorithm that no one else can maintain is a risk. True engineering excellence lies in finding elegant solutions that are both computationally efficient and simple enough for another developer to understand.`,

  // 4. Developer Ergonomics & Keyboards (~190 words)
  `A developer's keyboard is more than just an input device; it is a direct interface between thought and execution. The pursuit of typing speed and accuracy is closely tied to ergonomic efficiency and physical comfort during long coding sessions. Mechanical keyboards, with their tactile switches and customized layouts, have become a cornerstone of developer culture. Whether typing on linear switches for smooth travel, tactile switches for a subtle bump, or clicky switches for acoustic feedback, the choice of keyboard is highly personal. Good typing posture, wrist support, and touch-typing techniques are essential to prevent repetitive strain injuries. By training our muscle memory, we eliminate the friction of searching for keys, allowing our hands to keep pace with our thoughts. Programmers who master key bindings, IDE shortcuts, and command-line interfaces minimize mouse interaction, maintaining a state of deep focus. This flow state, where the physical keyboard fades into the background and ideas flow directly onto the screen, is the peak of developer productivity. Investing time in keyboard ergonomics and typing speed pays lifetime dividends in comfort, speed, and focus.`,

  // 5. Open Source & Collaboration (~200 words)
  `Open source software is the bedrock of the modern web, built on a foundation of global collaboration, shared knowledge, and mutual trust. Every day, millions of developers contribute to projects maintained by people they have never met, creating powerful libraries and frameworks that run our global infrastructure. Contributing to open source is an excellent way to hone coding skills, learn from peer code reviews, and build a professional portfolio. It requires not only technical proficiency but also strong communication skills to draft clear pull requests, write comprehensive documentation, and participate in technical discussions. Maintaining an open-source project involves managing issues, triaging bug reports, and fostering a welcoming community. The success of these projects relies on contributors who dedicate their time to fixing bugs, adding features, and writing tutorials. Through this open exchange of ideas, the software community drives innovation faster than any single corporation could. It teaches us the values of transparency, peer review, and cooperative problem-solving. By giving back to the projects we rely on, we participate in a virtuous cycle that elevates the entire software industry.`
];

export const getRandomParagraph = (): string => {
  const randomIndex = Math.floor(Math.random() * DEVELOPER_PARAGRAPHS.length);
  return DEVELOPER_PARAGRAPHS[randomIndex];
};
